version: "3"

services:
  ping:
    image: andou1984/dt01-tspingpong
    ports:
      - "8081:80"
    environment:
      EXPOSED_PORT: 80
      MESSAGE: PiNg

  pong:
    image: andou1984/dt01-tspingpong
    ports:
      - "8082:80"
    environment:
      EXPOSED_PORT: 80
      MESSAGE: pOnG

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
