apiVersion: v1
kind: Service
metadata:
  labels:
    app: ping
  name: ping
  namespace: pingpong
spec:
  type: NodePort
  ports:
    - name: "ping-service"
      port: 8081
      targetPort: 80
      nodePort: 30081
  selector:
    app: ping
