apiVersion: v1
kind: Service
metadata:
  labels:
    app: pong
  name: pong
  namespace: pingpong
spec:
  type: NodePort
  ports:
    - name: "pong-service"
      port: 8082
      targetPort: 80
      nodePort: 30082
  selector:
    app: pong
